servers:
- description: Local
  url: 'http://localhost:5006'
components:
  schemas: { }
info:
  contact: { }
  description: user-api
  license:
    name: Apache 2.0
  title: 'Spring Socks: user-api'
  version: 0.0.1-SNAPSHOT
openapi: 3.0.1
paths: { }